In [2]:
# Question 1
import numpy as np
np.arange(2, 51, 3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

In [18]:
#Question 2

lst = [] 
lst1 = []
  

  
# iterating till the range 
for i in range(0, 5): 
    ele = int(input()) 
    ele1 = int(input())
    lst.append(ele) # adding the element 
    lst1.append(ele1)
      
arr = np.array(lst)
arr1 = np.array(lst1)
np.sort(np.concatenate((arr,arr1)))


1
5
9
3
9
4
6
1
0
3


array([0, 1, 1, 3, 3, 4, 5, 6, 9, 9])

In [19]:
#Question 3

arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
                 
# Printing array dimensions
print("No. of dimensions: ", arr.ndim)
 
# Printing array size 
print("Size of array: ", arr.size)
                 


No. of dimensions:  2
Size of array:  6


In [27]:
#Question 4
x = np.array(([1,2],[3,4])) 
np.expand_dims(x, axis = 0)


array([[[1, 2],
        [3, 4]]])

In [38]:
#Question 5
a = np.square(np.arange(9).reshape(3, 3))
b=a*a
np.vstack((a,b))
np.hstack((a,b))

array([[   0,    1,    4,    0,    1,   16],
       [   9,   16,   25,   81,  256,  625],
       [  36,   49,   64, 1296, 2401, 4096]], dtype=int32)

In [42]:
#Question 6

my_list = [10, 20, 30, 40, 20, 50, 60, 40]
print("Original List : ",my_list)
my_set = set(my_list)
my_new_list = list(my_set)
print("List of unique numbers : ",my_new_list)
print("No of unique items in the list are:", len(my_new_list)) 

Original List :  [10, 20, 30, 40, 20, 50, 60, 40]
List of unique numbers :  [40, 10, 50, 20, 60, 30]
No of unique items in the list are: 6
